include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false
    use_key_in_widget_constructors: true
    prefer_final_fields: true
    sort_child_properties_last: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
